### ISSUE TITLE
Using doctrine instead of laminas-db

### ISSUE THREAD

**Issue by jarrettj** [kokspflanze/BjyAuthorize#38]
Hey,

Good day.

How do we get this to work with doctrine and not laminas-db? I seem to get the following error:

```
Notice: Undefined index: db in /var/www/html/vendor/laminas/laminas-db/src/Adapter/AdapterServiceFactory.php on line 21

Fatal error: Uncaught Laminas\Db\Adapter\Exception\InvalidArgumentException: The supplied or instantiated driver object does not implement Laminas\Db\Adapter\Driver\DriverInterface in /var/www/html/vendor/laminas/laminas-db/src/Adapter/Adapter.php:75 Stack trace: 
#0 /var/www/html/vendor/laminas/laminas-db/src/Adapter/AdapterServiceFactory.php(21): Laminas\Db\Adapter\Adapter->__construct(NULL) #1 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): Laminas\Db\Adapter\AdapterServiceFactory->__invoke(Object(Laminas\ServiceManager\ServiceManager), 'Laminas\\Db\\Adap...', NULL) 
#2 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate('Laminas\\Db\\Adap...') 
#3 /var/www/html/vendor/kokspflanze/bjy-authorize/src/Service/LmcUserLaminasDbIdentityProviderServiceFactory.php(24): Laminas\ServiceManager\ServiceManager->get('lmcuser_laminas...') 
#4 /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(613): BjyAut in /var/www/html/vendor/laminas/laminas-servicemanager/src/ServiceManager.php on line 620
```

Part of my config:
```
'bjyauthorize' => array(
        'unauthorized_strategy' => 'Application\Unauthorized',
        'default_role' => 'guest',
        'identity_provider' => 'BjyAuthorize\Provider\Identity\AuthenticationIdentityProvider',
        'role_providers' => array(
            'BjyAuthorize\Provider\Role\Config' => array(
                'guest' => array(),
...
```

But it should not try to use laminas-db as I have configuration for doctrine instead? Any help would be much appreciated. Busy migrating to laminas v3. Thanks.

Regards.
Jarrett

**Comment by kokspflanze** [comment]
Hi,

i use doctrine too, you just need to provide the right entities.

my config is like

```
        /* role providers simply provide a list of roles that should be inserted
         * into the Zend\Acl instance. the module comes with two providers, one
         * to specify roles in a config file and one to load roles using a
         * Zend\Db adapter.
         */
        'role_providers' => [
            // this will load roles from
            // the 'BjyAuthorize\Provider\Role\ObjectRepositoryProvider' service
            Provider\Role\ObjectRepositoryProvider::class => [
                // class name of the entity representing the role
                'role_entity_class' => \PServerCore\Entity\UserRole::class,
                // service name of the object manager
                'object_manager' => 'doctrine.entitymanager.orm_default',
            ],
        ],
```

The UserRole extends BjyAuthorize\Acl\HierarchicalRoleInterface, thats basic all.

You can also check https://github.com/kokspflanze/SmallUser thats my own little auth with laminas, doctrine and BjyAuthorize.
its not best but good to test this module=).

**Comment by jarrettj** [comment]
Thanks for the quick response, I know it is festive :). Gave that a try same outcome. Quick question, for this part of the code:
```
/**
 * You do not need to edit below this line
 */
return [
    'lmcuser' => $settings,
    'service_manager' => [
        'aliases' => [
            'lmcuser_laminas_db_adapter' => (isset($settings['laminas_db_adapter'])) ?
                $settings['laminas_db_adapter'] : \Laminas\Db\Adapter\Adapter::class,
        ],
    ],
];
```

Is that correct in the lmcuser.global.php file? Ain't it saying to use laminas-db there? 

Regards.
Jarrett

**Comment by kokspflanze** [comment]
it say laminas-db right.

if im right lmc user, use laminas-db as default, so you need to edit that for doctrine

**Comment by NiMeDia** [comment]
There is also a module https://github.com/LM-Commons/LmcUserDoctrineORM for running LmcUser with doctrine support.
